-- 코드를 입력하세요
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, TO_CHAR(BOOK.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE 
FROM BOOK, AUTHOR 
WHERE BOOK.CATEGORY = '경제' AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 
ORDER BY BOOK.PUBLISHED_DATE;